---
- name: This playbook is to install Docker
  hosts: "all"

  tasks:
    - name: Pre-req for Docker
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Pre package installation
      yum:
        name: yum-utils
        state: present

    - name: Repository setup
      get_url:
        dest: /etc/yum.repos.d/docker-ce.repo
        url: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Docker Installation
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
